AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ClientId:
    Type: String
    Description: Azure AD Client ID
  ClientSecret:
    Type: String
    NoEcho: true
    Description: Azure AD Client Secret
  TenantId:
    Type: String
    Description: Azure AD Tenant ID
  ListId:
    Type: String
    Description: SharePoint List ID
  SiteId:
    Type: String
    Description: SharePoint Site ID

Resources:
  SharePointSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: src/app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 900 # 15 minutos
      MemorySize: 512
      Environment:
        Variables:
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
          TENANT_ID: !Ref TenantId
          LIST_ID: !Ref ListId
          SITE_ID: !Ref SiteId
      Events:
        DailySync:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 8 * * ? *)' # 08:00 UTC todos os dias
            Description: Daily SharePoint synchronization

  SyncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${SharePointSyncFunction}'
      RetentionInDays: 30

Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref SharePointSyncFunction
